[project]
name = "photorec"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "flet[all]==0.28.3",
    "pillow>=11.3.0",
    "pillow-heif>=0.16.0",
    "reverse-geocode>=1.6",
    "imageio-ffmpeg>=0.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/photorec"]
